---
- name: vundle-install
  hosts: localhost
  tasks:
    - name: Install vundle plugin manager for Vim
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim