---
roles:
  - name: gantsign.helm
    src: https://github.com/gantsign/ansible-role-helm.git
  - name: gantsign.golang
    src: https://github.com/gantsign/ansible-role-golang.git
  - name: githubixx.kubectl
    src: https://github.com/githubixx/ansible-role-kubectl.git
