name: dotfiles-test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run make install
        run: |
          cd $GITHUB_WORKSPACE
          make install
