---
- name: apt-pacakges
  hosts: localhost
  tasks:
      
      - name: apt update
        apt:
          update_cache: yes
        become: true
      - name: apt upgrade
        apt:
          upgrade: yes
        become: true
      - name: Install a packages to setup docker
        apt:
            pkg:
            - curl
            - ca-certificates
            - gnupg
            - lsb-release
        become: true
      - name: Add docker gpg key
        shell: >
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        become: true
        always: true
      - name: Add Docker repository
        shell: >
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        become: true
        always: true
      - name: apt update after docker setup
        apt:
          update_cache: yes
        become: true
      - name: Install a list of packages
        apt:
            pkg:
            - base-files
            - base-passwd
            - bash
            - build-essential
            - cloud-init
            - containerd.io
            - dash
            - dbus-x11
            - debhelper
            - default-jdk
            - diffutils
            - docbook-xml
            - docbook-xsl
            - docker-ce-cli
            - docker-ce
            - dpkg-dev
            - eatmydata
            - findutils
            - fontconfig-config
            - fonts-dejavu-core
            - grep
            - gzip
            - hostname
            - init
            - libasyncns0
            - libdebconfclient0
            - libdrm-amdgpu1
            - libdrm-nouveau2
            - libdrm-radeon1
            - libeatmydata1
            - libedit-dev
            - libffi-dev
            - libflac8
            - libfontconfig1
            - libfontenc1
            - libgl1-mesa-dri
            - libgl1
            - libglapi-mesa
            - libglvnd0
            - libglx-mesa0
            - libglx0
            - libice6
            - libllvm12
            - libpciaccess0
            - libpulse0
            - libpulsedsp
            - libsensors-config
            - libsensors5
            - libsm6
            - libsndfile1
            - libsodium23
            - libsqlite3-dev
            - libssl-dev
            - libvorbisenc2
            - libvulkan1
            - libwayland-client0
            - libwrap0
            - libx11-xcb1
            - libxaw7
            - libxcb-dri2-0
            - libxcb-dri3-0
            - libxcb-glx0
            - libxcb-present0
            - libxcb-randr0
            - libxcb-shape0
            - libxcb-shm0
            - libxcb-sync1
            - libxcb-xfixes0
            - libxcomposite1
            - libxfixes3
            - libxft2
            - libxi6
            - libxinerama1
            - libxkbfile1
            - libxmu6
            - libxpm4
            - libxrandr2
            - libxrender1
            - libxshmfence1
            - libxt6
            - libxtst6
            - libxv1
            - libxxf86dga1
            - libxxf86vm1
            - mesa-vulkan-drivers
            - ncurses-base
            - ncurses-bin
            - ncurses-term
            - openssh-server
            - openssh-sftp-server
            - pkg-config
            - pulseaudio-utils
            - python3-distutils
            - python3-docutils
            - python3-importlib-metadata
            - python3-jinja2
            - python3-json-pointer
            - python3-jsonpatch
            - python3-jsonschema
            - python3-lib2to3
            - python3-markupsafe
            - python3-minimal
            - python3-more-itertools
            - python3-nacl
            - python3-pip
            - python3-pymacaroons
            - python3-pyrsistent
            - python3-serial
            - python3-setuptools
            - python3-zipp
            - python3
            - ruby-full
            - rsync
            - show-motd
            - ssh-import-id
            - sysvinit-utils
            - sqlite
            - update-motd
            - w3m
            - wslu
            - x11-common
            - x11-utils
            - xsltproc
            - libpq-dev
            - libmysqlclient-dev
        become: true
