---
- name: Configure dotfiles
  hosts: localhost
  tasks:
  - name: Change default shell
    ansible.builtin.command: usermod --shell /bin/zsh {{ ansible_user }}
    become: true
    changed_when: false
  - name: Stow dotfile packages
    shell: |
     stow bash
     stow git
     stow btop
     stow mdless
     stow powerline
     stow pypoetry
     stow tmux
     stow zsh
     stow vim
     stow nvim
     stow i3
     stow alacritty
     stow fonts
    args:
      chdir: "{{ playbook_dir }}/.."


