---
- name: go-pacakges
  hosts: localhost
  become: true
  
  roles:
    - name: gantsign.golang
      vars:
        golang_install_dir: /usr/local/go

  tasks:
    - name: install tinycare-tui
      command: /usr/local/go/bin/go install github.com/DMcP89/tinycare-tui@latest
