---
- name: go-pacakges
  hosts: localhost
  
  tasks:
    - name: Remove existing Go installation
      become: yes
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: Install latest version of Go
      become: yes
      ansible.builtin.shell: |
        curl -s https://go.dev/dl/ | grep linux-amd64.tar.gz | head -n 1 | grep -oP 'href="\K[^"]+' | xargs -I{} curl -LO https://go.dev{}
        tar -C /usr/local -xzf go*.linux-amd64.tar.gz
        rm go*.linux-amd64.tar.gz
      args:
        creates: /usr/local/go/bin/go
    - name: install tinycare-tui
      command: /usr/local/go/bin/go install github.com/DMcP89/tinycare-tui/cmd/tinycare-tui@latest
    - name: install lazygit
      command: /usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest 
