---
- name: npm-packages
  hosts: localhost
  tasks:
    - name: Install nvm
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
    - name: Install node and set version
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node && ln -s $(which npm) /home/{{ ansible_user_id }}/.local/bin/npm"
    - name: Install "tiny-care-terminal" node.js package.
      community.general.npm:
        name: tiny-care-terminal
        global: yes
        executable: "/home/{{ ansible_user_id }}/.local/bin/npm"
      become: true