---
- name: pip-packages
  hosts: localhost
  tasks:
    - name: Install Powerline
      pip:
        name: powerline-status
    - name: Install Powerline-gitstatus
      pip:
        name: powerline-gitstatus
    - name: Install poetry
      shell: >
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Clone pyenv repo
      git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: ~/.pyenv
    - name: Compile dynamic bash extension
      shell: >
        cd ~/.pyenv && src/configure && make -C src
    - name: Install pyenv-virtualenv
      git:
        repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
        dest: ~/.pyenv/plugins/pyenv-virtualenv
