---
- name: Install apt packages
  import_playbook: apt-packages.yml

- name: Install snap packages
  import_playbook: snap-packages.yml
  
- name: Copy dotfiles
  import_playbook: dotfile-copy.yml

- name: Install vundle
  import_playbook: vim-package-managers-install.yml

- name: Install gems
  import_playbook: gem-packages.yml

- name: Install node packages
  import_playbook: npm-packages.yml

- name: Install python packages
  import_playbook: pip-packages.yml

- name: Install Go
  import_playbook: go-packages.yml

- name: Install CLIs
  import_playbook: cli-packages.yml
