---
- name: snap-pacakges
  hosts: localhost
  tasks:
      - name: Install "nvim" with option --classic
        community.general.snap:
          name: nvim
          classic: true
      - name: Install dbeaver-ce 
        community.general.snap:
          name: dbeaver-ce
  become: true
